#!/bin/bash
output_file="student_encouragement.txt"
echo "안녕하세요, 학생 여러분!" > "$output_file"
echo "항상 열심히 노력하는 여러분을 응원합니다!" >> "$output_file"
echo "힘든 순간에도 포기하지 말고 끝까지 도전하세요." >> "$output_file"
echo "여러분은 할 수 있습니다! 화이팅!" >> "$output_file"
echo "오늘도 최선을 다하는 여러분을 응원합니다!" >> "$output_file"
echo "" >> "$output_file"
echo "당신의 꿈을 위해 계속 나아가세요!" >> "$output_file"
echo "응원의 메시지가 담긴 파일이 생성되었습니다: $output_file"
